image: alpine:latest

pages:
  stage: deploy
  tags:
    - docker  # On ajoute ce tag pour "appeler" le runner #3 de ta capture
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main