# Generated by Django 5.2.8 on 2026-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('invite', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_evenement', models.DateTimeField()),
                ('image', models.ImageField(upload_to='conferences/')),
                ('lien_inscription', models.URLField(blank=True, null=True)),
                ('est_passee', models.BooleanField(default=False)),
            ],
        ),
    ]
