# Generated by Django 5.2.8 on 2026-01-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du membre', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour ne plus recevoir les mails temporairement')),
            ],
            options={
                'verbose_name': 'Destinataire des messages du formulaire',
                'verbose_name_plural': 'Destinataires des messages du formulaire',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(help_text="Nom de l'intervenant ou nom du projet", max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(default='Politique', max_length=100)),
                ('type_evenement', models.CharField(choices=[('CONF', 'Conférence'), ('TABLE', 'Table Ronde'), ('WORK', 'Atelier / Workshop'), ('HACK', 'Hackathon'), ('TRIP', "Voyage d'étude"), ('AUTRE', 'Autre')], default='CONF', max_length=10)),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin (optionnel)')),
                ('horaires_precision', models.CharField(blank=True, help_text="Ex: 'Toute la journée' ou '14h-18h'", max_length=100)),
                ('lieu', models.CharField(default='Amphi Michelin', max_length=200)),
                ('image', models.ImageField(upload_to='evenements/')),
                ('lien_inscription', models.URLField(blank=True, help_text='Lien vers la billetterie ou Lydia')),
                ('est_publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-date_debut'],
            },
        ),
    ]
