# Generated by Django 5.2.8 on 2026-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='lien_inscription',
        ),
        migrations.AddField(
            model_name='conference',
            name='categorie',
            field=models.CharField(default='Politique', max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='lieu',
            field=models.CharField(default='Amphi Michelin', max_length=200),
        ),
    ]
