# Generated by Django 5.2.8 on 2026-01-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='lien_inscription',
            field=models.URLField(blank=True, help_text='Lien vers la billetterie (Lydia, Shotgun, etc.)', null=True),
        ),
    ]
