# Generated by Django 5.2.8 on 2026-01-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_conference_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du membre (ex: Responsable Partenariats)', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour ne plus recevoir les mails temporairement')),
            ],
            options={
                'verbose_name': 'Destinataire des messages',
                'verbose_name_plural': 'Destinataires des messages',
            },
        ),
    ]
