# Generated by Django 5.2.8 on 2026-01-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evenement_lien_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='equipe/')),
                ('ordre', models.PositiveIntegerField(default=100, help_text='Plus petit nombre = apparaît en premier')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
