# Generated by Django 5.2.8 on 2026-01-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_promotion', models.CharField(default='2026', help_text="L'année affichée pour l'équipe (ex: 2026)", max_length=4)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
