# Generated by Django 5.2.8 on 2026-01-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrecipient',
            options={'verbose_name': 'Destinataire des messages du formulaire', 'verbose_name_plural': 'Destinataires des messages du formulaire'},
        ),
        migrations.AlterField(
            model_name='contactrecipient',
            name='nom',
            field=models.CharField(help_text='Nom du membre', max_length=100),
        ),
    ]
