# Generated by Django 5.2.8 on 2026-01-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactrecipient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(default='Politique', max_length=100)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(default='Amphi Michelin', max_length=200)),
                ('image', models.ImageField(upload_to='evenements/')),
                ('est_passee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
