# Generated by Django 5.2.8 on 2026-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configurationsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partenaires/')),
                ('lien', models.URLField(blank=True, help_text='Lien vers leur site web')),
                ('ordre', models.PositiveIntegerField(default=100, help_text='Petit nombre = apparaît en premier')),
                ('taille_ajustement', models.PositiveIntegerField(default=100, help_text="En % : permet d'équilibrer les logos (ex: 80 pour un logo trop massif, 120 pour un logo trop fin)")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
