# Generated by Django 5.2.8 on 2026-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(help_text='Nom de la personnalité (ex: Jean-Marc Jancovici)', max_length=200)),
                ('url_youtube', models.URLField(help_text='Lien complet de la vidéo (ex: https://www.youtube.com/watch?v=...)')),
                ('ordre', models.PositiveIntegerField(default=100, help_text='Plus petit nombre = apparaît en premier')),
            ],
            options={
                'verbose_name': 'Replay Vidéo',
                'ordering': ['ordre', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(help_text='Descritpion', max_length=400),
        ),
    ]
