# Generated by Django 6.0.1 on 2026-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_replay_alter_evenement_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsite',
            name='a_propos_paragraphe_1',
            field=models.TextField(blank=True, default='Fondée en 2014, Symposium est la tribune étudiante de CentraleSupélec. Chaque mois, nous invitons des personnalités du monde politique, économique, culturel et académique à participer à des conférences et débats, afin d’échanger sans filtre avec les étudiants.'),
        ),
        migrations.AddField(
            model_name='configurationsite',
            name='a_propos_paragraphe_2',
            field=models.TextField(blank=True, default='Symposium s’adresse en premier lieu aux étudiants de CentraleSupélec, auxquels s’ajoutent régulièrement ceux de l’ENS Paris-Saclay, de l’École Polytechnique et, plus largement, des établissements du Plateau de Saclay.'),
        ),
        migrations.AddField(
            model_name='configurationsite',
            name='a_propos_statement',
            field=models.TextField(blank=True, default='À l’heure où les enjeux contemporains deviennent toujours plus techniques, Symposium défend la conviction que les ingénieurs et scientifiques doivent être pleinement acteurs du débat démocratique.'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(default='Politique', help_text='Le petit texte couleur or', max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(help_text='Description', max_length=400),
        ),
    ]
