# Generated by Django 6.0.1 on 2026-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configurationsite_a_propos_paragraphe_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='texte_bouton_inscription',
            field=models.CharField(blank=True, default="S'inscrire / Billetterie", help_text="Texte affiché sur le bouton (ex: 'Réserver sa place', 'En savoir plus')", max_length=50),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='est_publie',
            field=models.BooleanField(default=True, help_text="Décocher pour masquer l'événement du site public"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lien_inscription',
            field=models.URLField(blank=True, help_text="Lien vers la billetterie ou l'événement", null=True),
        ),
    ]
