# Generated by Django 5.2.17 on 2026-10-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evenement_texte_bouton_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Jean-Marc Jancovici', max_length=200)),
                ('fonction', models.CharField(blank=True, help_text='Ex: Président du Shift Project', max_length=255)),
                ('date_venue', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text="Court résumé de l'intervention")),
                ('categorie', models.CharField(choices=[('politique', 'Politique & Diplomatie'), ('economie', 'Économie & Entreprise'), ('sciences', 'Sciences, Climat & Énergie'), ('culture', 'Culture & Société')], default='economie', max_length=50)),
                ('youtube_url', models.URLField(help_text='Lien complet de la vidéo YouTube', max_length=500)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Pour forcer l'ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Invité',
                'verbose_name_plural': 'Invités',
                'ordering': ['-date_venue', 'ordre'],
            },
        ),
        migrations.AlterField(
            model_name='evenement',
            name='est_publie',
            field=models.BooleanField(default=True, help_text='Décocher pour passer en brouillon'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='texte_bouton_inscription',
            field=models.CharField(blank=True, default="S'inscrire / Billetterie", max_length=50),
        ),
    ]
