# Generated by Django 5.2.17 on 2026-10-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_invite_alter_evenement_est_publie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['ordre', '-date_venue'], 'verbose_name': 'Invité', 'verbose_name_plural': 'Invités'},
        ),
    ]
